# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6e633b7e5eef2d72251f18dd1bf41f83b1b91f292ae98a9acdcbb253a0e61d6af351d2cc343df1a770e2fb95219cd3840e0c2f1b3b501b2910573b04ec120d12

test:
  secret_key_base: 3151a90f0004105a015ab9f481c593d6cb71492dacd184e889cf73a7df8f4b4d0b34436c46d7162d49e84de9dce564454937fa4d0b2a05f2f88706128ae3b77d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
